apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    project: roboshop
    component: mongodb
    tier: database
spec:
  replicas: {{ .Values.deployment.replicas }}  # Changed to lowercase 'd'
  selector:
    matchLabels:
      project: roboshop
      component: mongodb
      tier: database
  template:
    metadata:
      labels:
        project: roboshop
        component: mongodb
        tier: database
    spec:
      containers:
      - name: mongodb
        image: {{ .Values.deployment.imageVersion }} # Changed to lowercase 'd'
        ports:
        - containerPort: 27017

