apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    env: dev
    component: mongodb
    tier: db
spec:
  replicas: {{ .Values.Deployment.replicas}}
  selector:
    matchLabels:
      project: roboshop
      env: dev
      component: mongodb
      tier: db
  template:
    metadata:
      labels:
        project: roboshop
        env: dev
        component: mongodb
        tier: db
    spec:
      containers:
        - name: mongodb
          image: {{ .Values.Deployment.image }}:{{ .Values.Deployment.imageVersion }}
          ports:
            - containerPort: 27017
              name: mongodb
