apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    env: dev
    component: mongodb
    tier: db
spec:
  selector:
    project: roboshop
    env: dev
    component: mongodb
    tier: db
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb