apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    env: dev
    component: catalogue
    tier: backend
spec: 
  selector:
    project: roboshop
    env: dev
    component: catalogue
    tier: backend
  ports:
    - port: 8080
      targetPort: 8080
      name: catalogue